#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Oct 20, 2023 06:40:17 PM +07  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m47" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 777x582+253+52
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1284 1005
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "APRSTHURSDAY"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "TopLevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    frame "$top.fra47" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 125 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 225 
    vTcl:DefineAlias "$top.fra47" "Frame1" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra47
    text "$site_3_0.tex48" \
        -background white -font "TkTextFont" -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief solid -selectbackground #c4c4c4 \
        -selectforeground black -width 104 -wrap word 
    $site_3_0.tex48 configure -font "TkTextFont"
    $site_3_0.tex48 insert end text
    vTcl:DefineAlias "$site_3_0.tex48" "TextKissIp" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    text "$site_3_0.tex49" \
        -background white -font "TkTextFont" -foreground black -height 30 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief solid -selectbackground #c4c4c4 \
        -selectforeground black -width 104 -wrap word 
    $site_3_0.tex49 configure -font "TkTextFont"
    $site_3_0.tex49 insert end text
    vTcl:DefineAlias "$site_3_0.tex49" "TextKissPort" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    button "$site_3_0.but50" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "Connect" -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Connect" 
    vTcl:DefineAlias "$site_3_0.but50" "Button1" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    label "$site_3_0.lab47" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify right -text "KISS IP :" 
    vTcl:DefineAlias "$site_3_0.lab47" "Label1" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    label "$site_3_0.lab48" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify right -text "KISS PORT :" 
    vTcl:DefineAlias "$site_3_0.lab48" "Label2" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    place $site_3_0.tex48 \
        -in $site_3_0 -x 0 -relx 0.489 -y 0 -rely 0.08 -width 0 \
        -relwidth 0.462 -height 0 -relheight 0.232 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex49 \
        -in $site_3_0 -x 0 -relx 0.489 -y 0 -rely 0.4 -width 0 \
        -relwidth 0.462 -height 0 -relheight 0.24 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.489 -y 0 -rely 0.72 -width 97 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.222 -y 0 -rely 0.08 -width 0 \
        -relwidth 0.24 -height 0 -relheight 0.168 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.133 -y 0 -rely 0.4 -width 0 \
        -relwidth 0.329 -height 0 -relheight 0.168 -anchor nw \
        -bordermode ignore 
    menu "$top.m47" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    frame "$top.fra48" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 125 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 335 
    vTcl:DefineAlias "$top.fra48" "Frame2" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    set site_3_0 $top.fra48
    text "$site_3_0.tex49" \
        -background white -font "TkTextFont" -foreground black -height 34 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief solid -selectbackground #c4c4c4 \
        -selectforeground black -width 234 -wrap word 
    $site_3_0.tex49 configure -font "TkTextFont"
    $site_3_0.tex49 insert end text
    vTcl:DefineAlias "$site_3_0.tex49" "TextMessages" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    text "$site_3_0.tex50" \
        -background white -font "TkTextFont" -foreground black -height 34 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief solid -selectbackground #c4c4c4 \
        -selectforeground black -width 234 -wrap word 
    $site_3_0.tex50 configure -font "TkTextFont"
    $site_3_0.tex50 insert end text
    vTcl:DefineAlias "$site_3_0.tex50" "TextBeacon" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    label "$site_3_0.lab51" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Messages : " 
    vTcl:DefineAlias "$site_3_0.lab51" "Label3" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    label "$site_3_0.lab52" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Beacon : " 
    vTcl:DefineAlias "$site_3_0.lab52" "Label4" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    place $site_3_0.tex49 \
        -in $site_3_0 -x 0 -relx 0.269 -y 0 -rely 0.16 -width 0 \
        -relwidth 0.699 -height 0 -relheight 0.272 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex50 \
        -in $site_3_0 -x 0 -relx 0.269 -y 0 -rely 0.56 -width 0 \
        -relwidth 0.699 -height 0 -relheight 0.272 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.03 -y 0 -rely 0.16 -width 0 \
        -relwidth 0.191 -height 0 -relheight 0.168 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.06 -y 0 -rely 0.64 -width 0 \
        -relwidth 0.161 -height 0 -relheight 0.168 -anchor nw \
        -bordermode ignore 
    button "$top.but54" \
        -activebackground $vTcl(analog_color_m) -activeforeground black \
        -background $vTcl(actual_gui_bg) -command "SendMesg" -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text "Send Messages" 
    vTcl:DefineAlias "$top.but54" "Button2" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    text "$top.tex55" \
        -background white -font "TkTextFont" -foreground black \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief solid -selectbackground #c4c4c4 \
        -selectforeground black -width 64 -wrap word 
    $top.tex55 configure -font "TkTextFont"
    $top.tex55 insert end text
    vTcl:DefineAlias "$top.tex55" "TextBeaconInterval" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    label "$top.lab56" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Interval : " 
    vTcl:DefineAlias "$top.lab56" "Label5" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    label "$top.lab57" \
        -activebackground #f9f9f9 -activeforeground SystemButtonText \
        -anchor w -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text "Logs" 
    vTcl:DefineAlias "$top.lab57" "Label6" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    text "$top.tex48" \
        -background white -font "TkTextFont" -foreground black -height 324 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -relief solid -selectbackground #c4c4c4 \
        -selectforeground black -width 733 -wrap word 
    $top.tex48 configure -font "TkTextFont"
    $top.tex48 insert end text
    vTcl:DefineAlias "$top.tex48" "Text1" vTcl:WidgetProc "TopLevel1" 1
### SPOT dump_widget_opt A
    vTcl::widgets::ttk::scrolledtext::CreateCmd "$top.scr50" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 225 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 335 
    vTcl:DefineAlias "$top.scr50" "Scrolledtext1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A

    $top.scr50.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra47 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.022 -width 0 -relwidth 0.375 \
        -height 0 -relheight 0.278 -anchor nw -bordermode ignore 
    place $top.fra48 \
        -in $top -x 0 -relx 0.417 -y 0 -rely 0.022 -width 0 -relwidth 0.558 \
        -height 0 -relheight 0.278 -anchor nw -bordermode ignore 
    place $top.but54 \
        -in $top -x 0 -relx 0.667 -y 0 -rely 0.333 -width 167 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.tex55 \
        -in $top -x 0 -relx 0.533 -y 0 -rely 0.333 -width 0 -relwidth 0.107 \
        -height 0 -relheight 0.053 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.433 -y 0 -rely 0.333 -width 0 -relwidth 0.09 \
        -height 0 -relheight 0.069 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.333 -width 0 -relwidth 0.107 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.tex48 \
        -in $top -x 0 -relx 0.026 -y 0 -rely 0.395 -width 0 -relwidth 0.943 \
        -height 0 -relheight 0.557 -anchor nw -bordermode ignore 
    place $top.scr50 \
        -in $top -x 0 -relx 0.217 -y 0 -rely 0.403 -width 0 -relwidth 0.608 \
        -height 0 -relheight 0.412 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

